-- Migration: Create all enums
-- Created at: 2026-09-13

CREATE TYPE "Role" AS ENUM ('DRIVER', 'ORGANIZER', 'ADMIN');
CREATE TYPE "ListingType" AS ENUM ('EVENT', 'RECURRING', 'COMMERCIAL');
CREATE TYPE "ListingStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "VehicleType" AS ENUM ('CAR', 'BIKE', 'OTHER');
CREATE TYPE "BookingStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW');
CREATE TYPE "PaymentStatus" AS ENUM ('CREATED', 'CAPTURED', 'FAILED', 'REFUNDED');
CREATE TYPE "SettlementStatus" AS ENUM ('PENDING', 'PROCESSING', 'PAID', 'DISPUTED');
